export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const REVIEW_REQUEST='REVIEW_REQUEST';
export const REVIEW_SUCCESS='REVIEW_SUCCESS';
export const REVIEW_FAIL='REVIEW_FAIL';
export const REVIEW_RESET='REVIEW_RESET';




export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';
export const CLEAR_ERROR='CLEAR_ERROR';